variant = "loose"

[[issues]]
file = "tests/Day1bTest.php"
code = "invalid-return-tag"
message = "Failed to resolve `@return` type string."
count = 2

[[issues]]
file = "tests/Day1bTest.php"
code = "less-specific-nested-argument-type"
message = 'Argument type mismatch for argument #1 of `Ewald\AdventOfCode2025\Day1B::processstrings`: expected `array<array-key, string>`, but provided type `array<array-key, mixed>` is less specific.'
count = 1

[[issues]]
file = "tests/Day2aTest.php"
code = "invalid-return-tag"
message = "Failed to resolve `@return` type string."
count = 2

[[issues]]
file = "tests/Day2bTest.php"
code = "invalid-return-tag"
message = "Failed to resolve `@return` type string."
count = 2
