variant = "loose"

[[issues]]
file = "run/day1a.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 1

[[issues]]
file = "run/day1b.php"
code = "no-shorthand-ternary"
message = "Use of the shorthand ternary operator."
count = 1

[[issues]]
file = "run/day2a.php"
code = "no-shorthand-ternary"
message = "Use of the shorthand ternary operator."
count = 1

[[issues]]
file = "run/day2b.php"
code = "no-shorthand-ternary"
message = "Use of the shorthand ternary operator."
count = 1

[[issues]]
file = "src/Day1B.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "tests/Day1bTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 2

[[issues]]
file = "tests/Day2aTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 3

[[issues]]
file = "tests/Day2aTest.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1

[[issues]]
file = "tests/Day2bTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 3

[[issues]]
file = "tests/Day2bTest.php"
code = "no-boolean-flag-parameter"
message = "Avoid boolean flag parameters."
count = 1
